name: CI/CD

on:
  push:
    branches:
      - "main"
    tags:
      - "v.*.*.*"

jobs:
  windows-build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build executable
        run: yarn build:win

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: Windows Setup
          path: ./dist/Setup_Green_Screen_Pomodoro_v*.exe

  linux-build:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build executable
        run: yarn build:linux

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: Linux Setup
          path: ./dist/Setup_Green_Screen_Pomodoro_v*.*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        permissions:
          contents: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}-${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Linux Setup.zip
          asset_name: Linux Setup ${{ github.ref_name }}.zip
          asset_content_type: application/zip

  macos-build:
    name: Build on MacOS
    runs-on: macos-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build executable
        run: yarn build:mac

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: MacOS Setup
          path: ./dist/Setup_Green_Screen_Pomodoro_v*.dmg
