name: Build Electron App and Release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  windows-build:
    name: Build on Windows
    id: windows_build
    runs-on: windows-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build executable
        run: yarn build:win

  linux-build:
    name: Build on Linux
    id: linux_build
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build executable
        run: yarn build:linux

  macos-build:
    name: Build on MacOS
    id: macos_build
    runs-on: macos-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build executable
        run: yarn build:mac

  # release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: Just a release!
  #         draft: false
  #         prerelease: false
